VDWtranslate = VDWtranslate or {}
VDWtranslate.Global = VDWtranslate.Global or {}
local base = {
	ADDON_IS_STATE = "The addon %s is %s.",
	COMBAT_LOCKDOWN = "You can't do that while in combat!",
	MOVING_LOCKDOWN = "You can't do that while you're moving!",

	OPEN_SETTINGS_MAIN = "Open the main settings panel.",
	DRAG_ME_TO_MOVE = "and drag to move me!",

	LEFT_CLICK = "Left Click",
	RIGHT_CLICK = "Right Click",

	LOCKED = "Locked",
	UNLOCKED = "Unlocked",

	BAR = "Bar",
	ICON = "Icon",
	BORDER = "Border",

	HIDE = "Hide",
	SHOW = "Show",

	TOPLEFT = "Top Left",
	LEFT = "Left",
	BOTTOMLEFT = "Bottom Left",
	TOP = "Top",
	CENTER = "Center",
	BOTTOM = "Bottom",
	TOPRIGHT = "Top Right",
	RIGHT = "Right",
	BOTTOMRIGHT = "Bottom Right",

	BOTH = "Both",

	DEFAULT = "Default",
	CUSTOM = "Custom",
	CLASSIC = "Classic",
	MODERN = "Modern",
	CLASS = "Class",
	CLASS_SQUARE = "Class Square",
	CLASS_ROUND = "Class Round",
	FACTION = "Faction",
	FACTION_ROUND = "Faction Round",
	FACTION_OLD = "Faction Old",
	FACTION_NEW = "Faction New",
	HERO = "Hero",
	BANNER = "Banner",
	RUNES = "Runes",
	SPELL_SCHOOL = "Spell School",
	STANDARD = "Standard",
	REVERSED = "Reversed",
	ASCENDING = "Ascending",
	DESCENDING = "Descending",
	UPWARD = "Upward",
	DOWNWARD = "Downward",
}
VDWtranslate.Translation = {
	esMX = {
		ADDON_IS_STATE = "El addon %s está %s.",
		COMBAT_LOCKDOWN = "¡No puedes hacer eso en combate!",
		MOVING_LOCKDOWN = "¡No puedes hacer eso mientras te mueves!",

		OPEN_SETTINGS_MAIN = "Abre el panel principal de ajustes.",
		DRAG_ME_TO_MOVE = "¡y arrástrame para moverme!",

		LEFT_CLICK = "Clic izquierdo",
		RIGHT_CLICK = "Clic derecho",

		LOCKED = "Bloqueado",
		UNLOCKED = "Desbloqueado",

		BAR = "Barra",
		ICON = "Icono",
		BORDER = "Borde",

		HIDE = "Ocultar",
		SHOW = "Mostrar",

		TOPLEFT = "Arriba izquierda",
		LEFT = "Izquierda",
		BOTTOMLEFT = "Abajo izquierda",
		TOP = "Arriba",
		CENTER = "Centro",
		BOTTOM = "Abajo",
		TOPRIGHT = "Arriba derecha",
		RIGHT = "Derecha",
		BOTTOMRIGHT = "Abajo derecha",

		BOTH = "Ambos",

		DEFAULT = "Predeterminado",
		CUSTOM = "Personalizado",
		CLASSIC = "Clásico",
		MODERN = "Moderno",
		CLASS = "Clase",
		CLASS_SQUARE = "Clase cuadrada",
		CLASS_ROUND = "Clase redonda",
		FACTION = "Facción",
		FACTION_ROUND = "Facción redonda",
		FACTION_OLD = "Facción antigua",
		FACTION_NEW = "Facción nueva",
		HERO = "Héroe",
		BANNER = "Estandarte",
		RUNES = "Runas",
		SPELL_SCHOOL = "Escuela de magia",
		STANDARD = "Estándar",
		REVERSED = "Invertido",
		ASCENDING = "Ascendente",
		DESCENDING = "Descendente",
		UPWARD = "Hacia arriba",
		DOWNWARD = "Hacia abajo",
	},
	ptBR = {
		ADDON_IS_STATE = "O addon %s está %s.",
		COMBAT_LOCKDOWN = "Você não pode fazer isso em combate!",
		MOVING_LOCKDOWN = "Você não pode fazer isso enquanto se move!",

		OPEN_SETTINGS_MAIN = "Abra o painel principal de configurações.",
		DRAG_ME_TO_MOVE = "e me arraste para me mover!",

		LEFT_CLICK = "Clique esquerdo",
		RIGHT_CLICK = "Clique direito",

		LOCKED = "Bloqueado",
		UNLOCKED = "Desbloqueado",

		BAR = "Barra",
		ICON = "Ícone",
		BORDER = "Borda",

		HIDE = "Ocultar",
		SHOW = "Mostrar",

		TOPLEFT = "Superior esquerdo",
		LEFT = "Esquerda",
		BOTTOMLEFT = "Inferior esquerdo",
		TOP = "Superior",
		CENTER = "Centro",
		BOTTOM = "Inferior",
		TOPRIGHT = "Superior direito",
		RIGHT = "Direita",
		BOTTOMRIGHT = "Inferior direito",

		BOTH = "Ambos",

		DEFAULT = "Padrão",
		CUSTOM = "Personalizado",
		CLASSIC = "Clássico",
		MODERN = "Moderno",
		CLASS = "Classe",
		CLASS_SQUARE = "Classe quadrada",
		CLASS_ROUND = "Classe redonda",
		FACTION = "Facção",
		FACTION_ROUND = "Facção redonda",
		FACTION_OLD = "Facção antiga",
		FACTION_NEW = "Facção nova",
		HERO = "Herói",
		BANNER = "Estandarte",
		RUNES = "Runas",
		SPELL_SCHOOL = "Escola de magia",
		STANDARD = "Padrão",
		REVERSED = "Invertido",
		ASCENDING = "Crescente",
		DESCENDING = "Decrescente",
		UPWARD = "Para cima",
		DOWNWARD = "Para baixo",
	},
	frFR = {
		ADDON_IS_STATE = "L'addon %s est %s.",
		COMBAT_LOCKDOWN = "Vous ne pouvez pas faire ça en combat !",
		MOVING_LOCKDOWN = "Vous ne pouvez pas faire ça en vous déplaçant !",

		OPEN_SETTINGS_MAIN = "Ouvrez le panneau principal des options.",
		DRAG_ME_TO_MOVE = "et faites-moi glisser pour me déplacer !",

		LEFT_CLICK = "Clic gauche",
		RIGHT_CLICK = "Clic droit",

		LOCKED = "Verrouillé",
		UNLOCKED = "Déverrouillé",

		BAR = "Barre",
		ICON = "Icône",
		BORDER = "Bordure",

		HIDE = "Masquer",
		SHOW = "Afficher",

		TOPLEFT = "Haut gauche",
		LEFT = "Gauche",
		BOTTOMLEFT = "Bas gauche",
		TOP = "Haut",
		CENTER = "Centre",
		BOTTOM = "Bas",
		TOPRIGHT = "Haut droit",
		RIGHT = "Droite",
		BOTTOMRIGHT = "Bas droit",

		BOTH = "Les deux",

		DEFAULT = "Par défaut",
		CUSTOM = "Personnalisé",
		CLASSIC = "Classique",
		MODERN = "Moderne",
		CLASS = "Classe",
		CLASS_SQUARE = "Classe carrée",
		CLASS_ROUND = "Classe ronde",
		FACTION = "Faction",
		FACTION_ROUND = "Faction ronde",
		FACTION_OLD = "Faction ancienne",
		FACTION_NEW = "Faction nouvelle",
		HERO = "Héros",
		BANNER = "Bannière",
		RUNES = "Runes",
		SPELL_SCHOOL = "École de magie",
		STANDARD = "Standard",
		REVERSED = "Inversé",
		ASCENDING = "Croissant",
		DESCENDING = "Décroissant",
		UPWARD = "Vers le haut",
		DOWNWARD = "Vers le bas",
	},
	deDE = {
		ADDON_IS_STATE = "Das Addon %s ist %s.",
		COMBAT_LOCKDOWN = "Das kannst du im Kampf nicht tun!",
		MOVING_LOCKDOWN = "Das kannst du nicht tun, während du dich bewegst!",

		OPEN_SETTINGS_MAIN = "Öffne das Hauptfenster der Einstellungen.",
		DRAG_ME_TO_MOVE = "und zieh mich, um mich zu verschieben!",

		LEFT_CLICK = "Linksklick",
		RIGHT_CLICK = "Rechtsklick",

		LOCKED = "Gesperrt",
		UNLOCKED = "Entsperrt",

		BAR = "Leiste",
		ICON = "Symbol",
		BORDER = "Rand",

		HIDE = "Ausblenden",
		SHOW = "Anzeigen",

		TOPLEFT = "Oben links",
		LEFT = "Links",
		BOTTOMLEFT = "Unten links",
		TOP = "Oben",
		CENTER = "Mitte",
		BOTTOM = "Unten",
		TOPRIGHT = "Oben rechts",
		RIGHT = "Rechts",
		BOTTOMRIGHT = "Unten rechts",

		BOTH = "Beide",

		DEFAULT = "Voreinstellung",
		CUSTOM = "Benutzerdefiniert",
		CLASSIC = "Klassisch",
		MODERN = "Modern",
		CLASS = "Klasse",
		CLASS_SQUARE = "Klasse Eckig",
		CLASS_ROUND = "Klasse Rund",
		FACTION = "Fraktion",
		FACTION_ROUND = "Fraktion Rund",
		FACTION_OLD = "Fraktion Alt",
		FACTION_NEW = "Fraktion Neu",
		HERO = "Held",
		BANNER = "Banner",
		RUNES = "Runen",
		SPELL_SCHOOL = "Zauberschule",
		STANDARD = "Standard",
		REVERSED = "Umgekehrt",
		ASCENDING = "Aufsteigend",
		DESCENDING = "Absteigend",
		UPWARD = "Nach oben",
		DOWNWARD = "Nach unten",
	},
	esES = {
		ADDON_IS_STATE = "El addon %s está %s.",
		COMBAT_LOCKDOWN = "¡No puedes hacer eso en combate!",
		MOVING_LOCKDOWN = "¡No puedes hacer eso mientras te mueves!",

		OPEN_SETTINGS_MAIN = "Abre el panel principal de ajustes.",
		DRAG_ME_TO_MOVE = "¡y arrástrame para moverme!",

		LEFT_CLICK = "Clic izquierdo",
		RIGHT_CLICK = "Clic derecho",

		LOCKED = "Bloqueado",
		UNLOCKED = "Desbloqueado",

		BAR = "Barra",
		ICON = "Icono",
		BORDER = "Borde",

		HIDE = "Ocultar",
		SHOW = "Mostrar",

		TOPLEFT = "Arriba izquierda",
		LEFT = "Izquierda",
		BOTTOMLEFT = "Abajo izquierda",
		TOP = "Arriba",
		CENTER = "Centro",
		BOTTOM = "Abajo",
		TOPRIGHT = "Arriba derecha",
		RIGHT = "Derecha",
		BOTTOMRIGHT = "Abajo derecha",

		BOTH = "Ambos",

		DEFAULT = "Predeterminado",
		CUSTOM = "Personalizado",
		CLASSIC = "Clásico",
		MODERN = "Moderno",
		CLASS = "Clase",
		CLASS_SQUARE = "Clase cuadrada",
		CLASS_ROUND = "Clase redonda",
		FACTION = "Facción",
		FACTION_ROUND = "Facción redonda",
		FACTION_OLD = "Facción antigua",
		FACTION_NEW = "Facción nueva",
		HERO = "Héroe",
		BANNER = "Estandarte",
		RUNES = "Runas",
		SPELL_SCHOOL = "Escuela de magia",
		STANDARD = "Estándar",
		REVERSED = "Invertido",
		ASCENDING = "Ascendente",
		DESCENDING = "Descendente",
		UPWARD = "Hacia arriba",
		DOWNWARD = "Hacia abajo",
	},
	itIT = {
		ADDON_IS_STATE = "L'addon %s è %s.",
		COMBAT_LOCKDOWN = "Non puoi farlo mentre sei in combattimento!",
		MOVING_LOCKDOWN = "Non puoi farlo mentre ti stai muovendo!",

		OPEN_SETTINGS_MAIN = "Apri il pannello principale delle impostazioni.",
		DRAG_ME_TO_MOVE = "e trascinami per spostarmi!",

		LEFT_CLICK = "Clic sinistro",
		RIGHT_CLICK = "Clic destro",

		LOCKED = "Bloccato",
		UNLOCKED = "Sbloccato",

		BAR = "Barra",
		ICON = "Icona",
		BORDER = "Bordo",

		HIDE = "Nascondi",
		SHOW = "Mostra",

		TOPLEFT = "In alto a sinistra",
		LEFT = "Sinistra",
		BOTTOMLEFT = "In basso a sinistra",
		TOP = "In alto",
		CENTER = "Centro",
		BOTTOM = "In basso",
		TOPRIGHT = "In alto a destra",
		RIGHT = "Destra",
		BOTTOMRIGHT = "In basso a destra",

		BOTH = "Entrambi",

		DEFAULT = "Predefinito",
		CUSTOM = "Personalizzato",
		CLASSIC = "Classico",
		MODERN = "Moderno",
		CLASS = "Classe",
		CLASS_SQUARE = "Classe quadrata",
		CLASS_ROUND = "Classe rotonda",
		FACTION = "Fazione",
		FACTION_ROUND = "Fazione rotonda",
		FACTION_OLD = "Fazione vecchia",
		FACTION_NEW = "Fazione nuova",
		HERO = "Eroe",
		BANNER = "Stendardo",
		RUNES = "Rune",
		SPELL_SCHOOL = "Scuola di magia",
		STANDARD = "Standard",
		REVERSED = "Invertito",
		ASCENDING = "Crescente",
		DESCENDING = "Decrescente",
		UPWARD = "Verso l'alto",
		DOWNWARD = "Verso il basso",
	},
	ruRU = {
		ADDON_IS_STATE = "Аддон %s: %s.",
		COMBAT_LOCKDOWN = "Вы не можете сделать это в бою!",
		MOVING_LOCKDOWN = "Вы не можете сделать это во время движения!",

		OPEN_SETTINGS_MAIN = "Открыть главную панель настроек.",
		DRAG_ME_TO_MOVE = "и перетащите меня, чтобы переместить!",

		LEFT_CLICK = "Левый клик",
		RIGHT_CLICK = "Правый клик",

		LOCKED = "Заблокирован",
		UNLOCKED = "Разблокирован",

		BAR = "Полоса",
		ICON = "Значок",
		BORDER = "Граница",

		HIDE = "Скрыть",
		SHOW = "Показать",

		TOPLEFT = "Слева сверху",
		LEFT = "Слева",
		BOTTOMLEFT = "Слева снизу",
		TOP = "Сверху",
		CENTER = "По центру",
		BOTTOM = "Снизу",
		TOPRIGHT = "Справа сверху",
		RIGHT = "Справа",
		BOTTOMRIGHT = "Справа снизу",

		BOTH = "Оба",

		DEFAULT = "По умолчанию",
		CUSTOM = "Пользовательский",
		CLASSIC = "Классический",
		MODERN = "Современный",
		CLASS = "Класс",
		CLASS_SQUARE = "Класс (квадрат)",
		CLASS_ROUND = "Класс (круг)",
		FACTION = "Фракция",
		FACTION_ROUND = "Фракция (круг)",
		FACTION_OLD = "Фракция (старая)",
		FACTION_NEW = "Фракция (новая)",
		HERO = "Герой",
		BANNER = "Знамя",
		RUNES = "Руны",
		SPELL_SCHOOL = "Школа магии",
		STANDARD = "Стандарт",
		REVERSED = "Обратный",
		ASCENDING = "По возрастанию",
		DESCENDING = "По убыванию",
		UPWARD = "Вверх",
		DOWNWARD = "Вниз",
	},
	zhCN = {
		ADDON_IS_STATE = "插件 %s 当前为%s。",
		COMBAT_LOCKDOWN = "战斗中无法这样做！",
		MOVING_LOCKDOWN = "移动时无法这样做！",

		OPEN_SETTINGS_MAIN = "打开主设置面板。",
		DRAG_ME_TO_MOVE = "并拖动来移动我！",

		LEFT_CLICK = "左键点击",
		RIGHT_CLICK = "右键点击",

		LOCKED = "已锁定",
		UNLOCKED = "已解锁",

		BAR = "条",
		ICON = "图标",
		BORDER = "边框",

		HIDE = "隐藏",
		SHOW = "显示",

		TOPLEFT = "左上",
		LEFT = "左侧",
		BOTTOMLEFT = "左下",
		TOP = "上方",
		CENTER = "中央",
		BOTTOM = "下方",
		TOPRIGHT = "右上",
		RIGHT = "右侧",
		BOTTOMRIGHT = "右下",

		BOTH = "两者",

		DEFAULT = "默认",
		CUSTOM = "自定义",
		CLASSIC = "经典",
		MODERN = "现代",
		CLASS = "职业",
		CLASS_SQUARE = "职业方形",
		CLASS_ROUND = "职业圆形",
		FACTION = "阵营",
		FACTION_ROUND = "阵营圆形",
		FACTION_OLD = "旧版阵营",
		FACTION_NEW = "新版阵营",
		HERO = "英雄",
		BANNER = "旗帜",
		RUNES = "符文",
		SPELL_SCHOOL = "法术学派",
		STANDARD = "标准",
		REVERSED = "反向",
		ASCENDING = "升序",
		DESCENDING = "降序",
		UPWARD = "向上",
		DOWNWARD = "向下",
	},
	zhTW = {
		ADDON_IS_STATE = "插件 %s 目前為%s。",
		COMBAT_LOCKDOWN = "戰鬥中無法這樣做！",
		MOVING_LOCKDOWN = "移動時無法這樣做！",

		OPEN_SETTINGS_MAIN = "打開主要設定面板。",
		DRAG_ME_TO_MOVE = "並拖曳來移動我！",

		LEFT_CLICK = "左鍵點擊",
		RIGHT_CLICK = "右鍵點擊",

		LOCKED = "已鎖定",
		UNLOCKED = "已解鎖",

		BAR = "條",
		ICON = "圖示",
		BORDER = "邊框",

		HIDE = "隱藏",
		SHOW = "顯示",

		TOPLEFT = "左上",
		LEFT = "左側",
		BOTTOMLEFT = "左下",
		TOP = "上方",
		CENTER = "中央",
		BOTTOM = "下方",
		TOPRIGHT = "右上",
		RIGHT = "右側",
		BOTTOMRIGHT = "右下",

		BOTH = "兩者",

		DEFAULT = "預設",
		CUSTOM = "自訂",
		CLASSIC = "經典",
		MODERN = "現代",
		CLASS = "職業",
		CLASS_SQUARE = "職業方形",
		CLASS_ROUND = "職業圓形",
		FACTION = "陣營",
		FACTION_ROUND = "陣營圓形",
		FACTION_OLD = "舊版陣營",
		FACTION_NEW = "新版陣營",
		HERO = "英雄",
		BANNER = "旗幟",
		RUNES = "符文",
		SPELL_SCHOOL = "法術學派",
		STANDARD = "標準",
		REVERSED = "反向",
		ASCENDING = "遞增",
		DESCENDING = "遞減",
		UPWARD = "向上",
		DOWNWARD = "向下",
	},
	koKR = {
		ADDON_IS_STATE = "애드온 %s 상태: %s.",
		COMBAT_LOCKDOWN = "전투 중에는 그렇게 할 수 없습니다!",
		MOVING_LOCKDOWN = "이동 중에는 그렇게 할 수 없습니다!",

		OPEN_SETTINGS_MAIN = "메인 설정 패널을 엽니다.",
		DRAG_ME_TO_MOVE = "그리고 드래그해서 이동하세요!",

		LEFT_CLICK = "왼쪽 클릭",
		RIGHT_CLICK = "오른쪽 클릭",

		LOCKED = "잠금",
		UNLOCKED = "잠금 해제",

		BAR = "바",
		ICON = "아이콘",
		BORDER = "테두리",

		HIDE = "숨기기",
		SHOW = "표시",

		TOPLEFT = "좌상단",
		LEFT = "좌측",
		BOTTOMLEFT = "좌하단",
		TOP = "상단",
		CENTER = "중앙",
		BOTTOM = "하단",
		TOPRIGHT = "우상단",
		RIGHT = "우측",
		BOTTOMRIGHT = "우하단",

		BOTH = "둘 다",

		DEFAULT = "기본값",
		CUSTOM = "사용자 지정",
		CLASSIC = "클래식",
		MODERN = "모던",
		CLASS = "직업",
		CLASS_SQUARE = "직업 사각형",
		CLASS_ROUND = "직업 원형",
		FACTION = "진영",
		FACTION_ROUND = "진영 원형",
		FACTION_OLD = "기존 진영",
		FACTION_NEW = "신규 진영",
		HERO = "영웅",
		BANNER = "배너",
		RUNES = "룬",
		SPELL_SCHOOL = "마법 계열",
		STANDARD = "표준",
		REVERSED = "반전",
		ASCENDING = "오름차순",
		DESCENDING = "내림차순",
		UPWARD = "위쪽",
		DOWNWARD = "아래쪽",
	},
	enUS = base,
}
local loc = GetLocale()
local o = VDWtranslate.Translation[loc]
if type(o) == "string" then
	o = VDWtranslate.Translation[o]
end
if type(o) ~= "table" then
	o = nil
end
for k, v in pairs(base) do
	VDWtranslate.Global[k] = (o and o[k]) or v
end
